[package]
name = "ds2_sl2_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
aes = "0.8"
cbc = "0.1"
byteorder = "1"
clap = { version = "4", features = ["derive"] }
md-5 = "0.10"   # crate name is "md-5"
dotenvy = "0.15"
hex = "0.4"
base64 = "0.22.1"
